### ISSUE TITLE
Problem with directory structure in pip package (theanolm/network/architectures/)

### ISSUE THREAD

**Issue by adbar** [senarvi/theanolm#17]
Hello,

I just installed theanolm with pip and it expects the architectures to be in **theanolm/network/architectures/** whereas they are in **theanolm/architectures/** , so that the program won't run:

Traceback (most recent call last):
  File "/usr/local/bin/theanolm", line 41, in <module>
    main()
  File "/usr/local/bin/theanolm", line 36, in main
    args.command_function(args)
  File "/usr/local/lib/python3.4/dist-packages/theanolm/commands/train.py", line 215, in train
    architecture = Architecture.from_package(args.architecture)
  File "/usr/local/lib/python3.4/dist-packages/theanolm/network/architecture.py", line 161, in from_package
    with open(description_path, 'rt', encoding='utf-8') as description_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/theanolm/network/architectures/lstm1500.arch'

Thank you

**Comment by senarvi** [comment]
Thanks for reporting. I made some changes in the package structure and forgot to update that path. It should work now. I uploaded a new version to pip. However, I'm currently developing the lattice decoder and haven't had time to test everything thoroughly, so I wouldn't be surprised if you'll find more bugs. Alternatively you can give a full path to an architecture file using the `--architecture` argument.

**Comment by adbar** [comment]
Thank you, it works now.
