### ISSUE TITLE
Getting models from each epoch

### ISSUE THREAD

**Issue by bplank** [senarvi/theanolm#22]
Hi @senarvi 
great work with theanolm, thanks.
I was wondering, is there an option to store the models of every epoch? (for now it overwrites MODELNAME each time)
Thanks!
Barbara

**Comment by senarvi** [comment]
There's no such option. Why would you want to do that?

**Comment by bplank** [comment]
Because I'm using it the LM to score for another task (where it's not ppl on the dev set).

**Comment by bplank** [comment]
But I see that other's don't have any advantage for such an option, thus closing it. Thanks!

**Comment by senarvi** [comment]
There are probably not so many people who need this option, but for a quick experiment, maybe you could just copy the file to a new name after each epoch, or each time the model is saved here:

https://github.com/senarvi/theanolm/blob/master/theanolm/training/trainer.py#L455

**Comment by bplank** [comment]
Excellent, thanks! I'll do that.

Another small note:
Running on a GPU works fine, but in order to get the code running on a CPU
I had to disable the exception block in bin/theanolm
that regards the following import:

`
from theano.gpuarray.type import ContextNotDefined
`

thanks!
