### ISSUE TITLE
No module named 'theano.gpuarray' while installing

### ISSUE THREAD

**Issue by EmadHelmi** [senarvi/theanolm#23]
When I want to install theanolm i got this error
```
theanolm train
Traceback (most recent call last):
  File "/usr/local/bin/theanolm", line 8, in <module>
    from theano.gpuarray.type import ContextNotDefined
ImportError: No module named 'theano.gpuarray'

```
I have installed theanolm on python3 correctly and I can import it without any problem

**Comment by senarvi** [comment]
This should already be fixed in the develop branch. I'll make a new release soon. If you want, you can try the develop branch (or copy bin/theanolm from there) and let me know if it works.

**Comment by senarvi** [comment]
I made a new release. I didn't test it with libgpuarray uninstalled, so please reopen the issue if the error persists.
